volumes:
  db_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fpgen
      POSTGRES_USER: fpgen
      POSTGRES_PASSWORD: fpgen
    ports:
      - 5432:5432